# # # name: My Workflow
# # # on:
# # #   push:
# # #     paths:
# # #       - 'worker/**'
# # #       - 'data-processors/**'
# # #       - 'product/**'
# # # # env:
# # #   # TRIGGERED_FOLDER: ${{ github.event.action }}
# # #   # TRIGGERED_FOLDER1: ${{ github.event.pusher }}
# # #   # folder: ${{ github.event.modified }}
# # # jobs:
# # #   my-job:
# # #     runs-on: ubuntu-latest
# # #     steps:
# # #       - name: Print github.event object
# # #         run: echo "${{ toJson(github.event) }}"
# # #       - name: Use triggered folder
# # #         run: |
# # #           echo "The triggered folder is $TRIGGERED_FOLDER"
# # #           echo "The triggered folder is $TRIGGERED_FOLDER1"
# # #           echo "$folder"

# # name: My Workflow

# # on:
# #   push:
# #     paths:
# #       - 'worker/**'
# #       - 'data-processors/**'

# # jobs:
# #   build:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@v2

# #       - name: Check if data was changed
# #         run: |
# #           git show --pretty="" --name-only $GITHUB_EVENT_AFTER
# #       - name: Check if worker was changed
# #         run: |
# #           git diff --name-only ${{ github.event.before }} ${{ github.event.after }}


# name: Workflow example

# env:
#   FOLDER1: worker
#   FOLDER2: asdasd
#   FOLDER3: asdasdasd
# on:

#   push:
#     branches:
#     - main
#     paths:
#     - '$FOLDER/**'
#     - ''data-processors/**''

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Check if data was changed
#         run: |
#           git show --pretty="" --name-only $GITHUB_EVENT_AFTER
#       - name: Check if worker was changed
#         run: |
#           git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for Changes
        run: |
          if [ -z "${{ github.event.paths }}" ]; then
            echo "No files were changed in this push event."
            exit 0
          else
            echo "Files were changed in this push event:"
            echo "${{ github.event.paths }}"
          fi
      - name: Identify Changed Folder
        run: |
          # Loop through each path in the list of modified paths
          for path in "${{ github.event.paths }}"; do
            # Check if the path starts with "worker/"
            if [[ $path == "worker/"* ]]; then
              echo "worker was changed"
              echo "$path"
              break
            fi
            # Check if the path starts with "product/"
            if [[ $path == "product/"* ]]; then
              echo "product was changed"
              echo "$path"
              break
            fi
            # Add additional checks for other folders as needed
          done
