name: My Workflow
on:
  push:
    paths:
      - 'worker/**'
      - 'data-processors/**'
      - 'product/**'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get folder name
        id: get_folder_name
        run: echo "::set-output name=folder_name::${{ github.event.inputs.paths }}"

      - name: Use folder name
        run: echo "The folder name is ${{ steps.get_folder_name.outputs.folder_name }}"