name: My Workflow
on:
  push:
    paths:
      - 'worker/**'
      - 'data-processors/**'
      - 'product/**'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get folder
        run: | 
          echo ${{ github.event.inputs.paths }}
          echo "${{ github.event.inputs.paths }}"
          echo GITHUB_ENV
      - name: Get folder name
        id: get_folder_name
        run: echo "::set-output name=folder_name::${{ github.event.inputs.paths }}"

      - name: Extract folder name
        id: extract_folder_name
        if: ${{ startsWith(steps.get_folder_name.outputs.folder_name, 'worker/') }}
        run: echo "::set-output name=folder_name::worker"
        