name: My Workflow
on:
  push:
    paths:
      - 'worker/**'
      - 'data-processors/**'
      - 'product/**'
env:
  path: ${{ github.action_path }}
  path1: $github.action_path

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get folder name
        id: get_folder_name
        run: echo "::set-output name=folder_name::${{ github.event.inputs.paths }}"
      - name: show folder_name
        run: echo  "${{ steps.get_folder_name.outputs.folder_name }}"

        