# # # name: My Workflow
# # # on:
# # #   push:
# # #     paths:
# # #       - 'worker/**'
# # #       - 'data-processors/**'
# # #       - 'product/**'
# # # # env:
# # #   # TRIGGERED_FOLDER: ${{ github.event.action }}
# # #   # TRIGGERED_FOLDER1: ${{ github.event.pusher }}
# # #   # folder: ${{ github.event.modified }}
# # # jobs:
# # #   my-job:
# # #     runs-on: ubuntu-latest
# # #     steps:
# # #       - name: Print github.event object
# # #         run: echo "${{ toJson(github.event) }}"
# # #       - name: Use triggered folder
# # #         run: |
# # #           echo "The triggered folder is $TRIGGERED_FOLDER"
# # #           echo "The triggered folder is $TRIGGERED_FOLDER1"
# # #           echo "$folder"

# # name: My Workflow

# # on:
# #   push:
# #     paths:
# #       - 'worker/**'
# #       - 'data-processors/**'

# # jobs:
# #   build:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@v2

# #       - name: Check if data was changed
# #         run: |
# #           git show --pretty="" --name-only $GITHUB_EVENT_AFTER
# #       - name: Check if worker was changed
# #         run: |
# #           git diff --name-only ${{ github.event.before }} ${{ github.event.after }}


name: Workflow example

on:

  push:
    branches:
    - main
    paths:
    - 'worker/**'
    - 'data-processors/**'
    - 'product/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if folder was changed
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | cut -d "/" -f1 > file.txt
          cat file.txt
      - name: Search for words
        run: |
          for variable in "worker" "data-processors" "product"; do
          if grep -q "variable" file.txt; then echo " --kubeconfig kubeconfig set image deployment/variable"; fi
          done



#           # if grep -q "worker" file.txt; then echo " --kubeconfig kubeconfig set image deployment/worker"; fi 
#           # if grep -q "data-processors" file.txt; then echo "--kubeconfig kubeconfig set image deployment/data-processors"; fi
#           # if grep -q "product" file.txt; then echo " --kubeconfig kubeconfig set image deployment/product"
#           # else if 
#           #   echo "There is no changes to set new image to deployment"
#           # fi

