# # # name: My Workflow
# # # on:
# # #   push:
# # #     paths:
# # #       - 'worker/**'
# # #       - 'data-processors/**'
# # #       - 'product/**'
# # # # env:
# # #   # TRIGGERED_FOLDER: ${{ github.event.action }}
# # #   # TRIGGERED_FOLDER1: ${{ github.event.pusher }}
# # #   # folder: ${{ github.event.modified }}
# # # jobs:
# # #   my-job:
# # #     runs-on: ubuntu-latest
# # #     steps:
# # #       - name: Print github.event object
# # #         run: echo "${{ toJson(github.event) }}"
# # #       - name: Use triggered folder
# # #         run: |
# # #           echo "The triggered folder is $TRIGGERED_FOLDER"
# # #           echo "The triggered folder is $TRIGGERED_FOLDER1"
# # #           echo "$folder"

# # name: My Workflow

# # on:
# #   push:
# #     paths:
# #       - 'worker/**'
# #       - 'data-processors/**'

# # jobs:
# #   build:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@v2

# #       - name: Check if data was changed
# #         run: |
# #           git show --pretty="" --name-only $GITHUB_EVENT_AFTER
# #       - name: Check if worker was changed
# #         run: |
# #           git diff --name-only ${{ github.event.before }} ${{ github.event.after }}


# name: Workflow example

# env:
#   FOLDER1: worker
#   FOLDER2: asdasd
#   FOLDER3: asdasdasd
# on:

#   push:
#     branches:
#     - main
#     paths:
#     - '$FOLDER/**'
#     - ''data-processors/**''

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Check if data was changed
#         run: |
#           git show --pretty="" --name-only $GITHUB_EVENT_AFTER
#       - name: Check if worker was changed
#         run: |
#           git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

on:
  push:
    branches:
      - 'main'
    paths:
      - 'worker/**'
      - 'product/**'
jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed-files.dirs }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true

  do-stuff:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.find-out-changes.outputs.dirs)}}
    needs:
      - find-out-changes
    steps:
      - uses: actions/checkout@v3
      - run: zip ${{ matrix.dir }} etc.