name: My Workflow
on:
  push:
    paths:
      - 'worker/**'
      - 'data-processors/**'
      - 'product/**'
# env:
#   path: ${{ github.action_path }}
#   path1: $github.action_path

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      TRIGGERED_FOLDER: ${{ github.event.inputs.paths }}
    steps:
      - name: Use triggered folder
        run: echo "The triggered folder is $TRIGGERED_FOLDER"

        