name: My Workflow
on:
  push:
    paths:
      - 'worker/**'
      - 'data-processors/**'
      - 'product/**'
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      TRIGGERED_FOLDER: ${{ github.push.inputs.paths }}
      TRIGGERED_FOLDER1: ${{ on.push.inputs.paths }}
    steps:
      - name: Use triggered folder
        run: |
          echo "The triggered folder is $TRIGGERED_FOLDER"
          echo "The triggered folder is $TRIGGERED_FOLDER1"

        