name: My Workflow
on:
  push:
    paths:
      - 'worker/**'
      - 'data-processors/**'
      - 'product/**'
env:
  TRIGGERED_FOLDER: ${{ github.event.action }}
  TRIGGERED_FOLDER1: ${{github.event.pusher}}
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Use triggered folder
        run: |
          echo "The triggered folder is $TRIGGERED_FOLDER"
          echo "The triggered folder is $TRIGGERED_FOLDER1"

        