name: My Workflow
on:
  push:
    paths:
      - 'worker/**'
      - 'data-processors/**'
      - 'product/**'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get folder name
        id: get_folder_name
        run: | 
          echo "::set-output name=folder_name::${{ github.event.inputs.paths }}"
          echo "${{ env.folder_name }}"