name: My Workflow
on:
  push:
    paths:
      - 'worker/**'
      - 'data-processors/**'
      - 'product/**'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get folder
        run: | 
          echo "action_state=yellow" >> "$GITHUB_ENV"
          echo $GITHUB_ENV

        